# Generated by Django 4.1.5 on 2023-10-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='prod_id',
            field=models.IntegerField(default=1),
        ),
    ]
